MODEL_PARAMS = \
    { 'aggregationInfo': { 'days': 0,
                           'fields': [],
                           'hours': 0,
                           'microseconds': 0,
                           'milliseconds': 0,
                           'minutes': 0,
                           'months': 0,
                           'seconds': 0,
                           'weeks': 0,
                           'years': 0},
      'model': 'HTMPrediction',
      'modelParams': { 'anomalyParams': { u'anomalyCacheRecords': None,
                                          u'autoDetectThreshold': None,
                                          u'autoDetectWaitRecords': None},
                       # Don't create the classifier since we don't need predictions.
                       'clEnable': True,
                       'clParams': { 'alpha': 0.01962508905154251,
                                     'verbosity': 0,
                                     'regionName': 'SDRClassifierRegion',
                                     'steps': '1'},
                       'inferenceType': 'TemporalAnomaly',
                       'sensorParams': { 'encoders': { '_classifierInput': { 'classifierOnly': True,
                                                                             'clipInput': True,
                                                                             'fieldname': 'class',
                                                                             'maxval': 2.0,
                                                                             'minval': 0.0,
                                                                             'n': 22,
                                                                             'name': '_classifierInput',
                                                                             'type': 'ScalarEncoder',
                                                                             'w': 21},
                                                       u'V1': { 'clipInput': True,
                                                                'fieldname': 'V1',
                                                                'maxval': 10.0,
                                                                'minval': -20.0,
                                                                'n': 50,
                                                                'name': 'V1',
                                                                'type': 'ScalarEncoder',
                                                                'w': 21},
                                                       u'V2': { 'clipInput': True,
                                                                'fieldname': 'V2',
                                                                'maxval': 10.0,
                                                                'minval': -20.0,
                                                                'n': 50,
                                                                'name': 'V2',
                                                                'type': 'ScalarEncoder',
                                                                'w': 21},
                                                       u'V3': { 'clipInput': True,
                                                                'fieldname': 'V3',
                                                                'maxval': 10.0,
                                                                'minval': -20.0,
                                                                'n': 50,
                                                                'name': 'V3',
                                                                'type': 'ScalarEncoder',
                                                                'w': 21},
                                                       u'V4': { 'clipInput': True,
                                                                'fieldname': 'V1',
                                                                'maxval': 10.0,
                                                                'minval': -20.0,
                                                                'n': 50,
                                                                'name': 'V1',
                                                                'type': 'ScalarEncoder',
                                                                'w': 21},
                                                       u'V5': { 'clipInput': True,
                                                                'fieldname': 'V2',
                                                                'maxval': 10.0,
                                                                'minval': -20.0,
                                                                'n': 50,
                                                                'name': 'V2',
                                                                'type': 'ScalarEncoder',
                                                                'w': 21},
                                                       u'V6': { 'clipInput': True,
                                                                'fieldname': 'V3',
                                                                'maxval': 10.0,
                                                                'minval': -20.0,
                                                                'n': 50,
                                                                'name': 'V3',
                                                                'type': 'ScalarEncoder',
                                                                'w': 21},
                                                       u'V7': { 'clipInput': True,
                                                                'fieldname': 'V1',
                                                                'maxval': 10.0,
                                                                'minval': -20.0,
                                                                'n': 50,
                                                                'name': 'V1',
                                                                'type': 'ScalarEncoder',
                                                                'w': 21},
                                                       u'V8': { 'clipInput': True,
                                                                'fieldname': 'V2',
                                                                'maxval': 10.0,
                                                                'minval': -20.0,
                                                                'n': 50,
                                                                'name': 'V2',
                                                                'type': 'ScalarEncoder',
                                                                'w': 21},
                                                       u'V9': { 'clipInput': True,
                                                                'fieldname': 'V3',
                                                                'maxval': 10.0,
                                                                'minval': -20.0,
                                                                'n': 50,
                                                                'name': 'V3',
                                                                'type': 'ScalarEncoder',
                                                                'w': 21},
                                                       u'V10': { 'clipInput': True,
                                                                'fieldname': 'V3',
                                                                'maxval': 10.0,
                                                                'minval': -20.0,
                                                                'n': 50,
                                                                'name': 'V3',
                                                                'type': 'ScalarEncoder',
                                                                'w': 21},
                                                       u'V11': { 'clipInput': True,
                                                                'fieldname': 'V1',
                                                                'maxval': 10.0,
                                                                'minval': -20.0,
                                                                'n': 50,
                                                                'name': 'V1',
                                                                'type': 'ScalarEncoder',
                                                                'w': 21},
                                                       u'V12': { 'clipInput': True,
                                                                'fieldname': 'V2',
                                                                'maxval': 10.0,
                                                                'minval': -20.0,
                                                                'n': 50,
                                                                'name': 'V2',
                                                                'type': 'ScalarEncoder',
                                                                'w': 21},
                                                       u'V13': { 'clipInput': True,
                                                                'fieldname': 'V3',
                                                                'maxval': 10.0,
                                                                'minval': -20.0,
                                                                'n': 50,
                                                                'name': 'V3',
                                                                'type': 'ScalarEncoder',
                                                                'w': 21},
                                                       u'V14': { 'clipInput': True,
                                                                'fieldname': 'V1',
                                                                'maxval': 10.0,
                                                                'minval': -20.0,
                                                                'n': 50,
                                                                'name': 'V1',
                                                                'type': 'ScalarEncoder',
                                                                'w': 21},
                                                       u'V15': { 'clipInput': True,
                                                                'fieldname': 'V2',
                                                                'maxval': 10.0,
                                                                'minval': -20.0,
                                                                'n': 50,
                                                                'name': 'V2',
                                                                'type': 'ScalarEncoder',
                                                                'w': 21},
                                                       u'V16': { 'clipInput': True,
                                                                'fieldname': 'V3',
                                                                'maxval': 10.0,
                                                                'minval': -20.0,
                                                                'n': 50,
                                                                'name': 'V3',
                                                                'type': 'ScalarEncoder',
                                                                'w': 21},
                                                       u'V17': { 'clipInput': True,
                                                                'fieldname': 'V1',
                                                                'maxval': 10.0,
                                                                'minval': -20.0,
                                                                'n': 50,
                                                                'name': 'V1',
                                                                'type': 'ScalarEncoder',
                                                                'w': 21},
                                                       u'V18': { 'clipInput': True,
                                                                'fieldname': 'V2',
                                                                'maxval': 10.0,
                                                                'minval': -20.0,
                                                                'n': 50,
                                                                'name': 'V2',
                                                                'type': 'ScalarEncoder',
                                                                'w': 21},
                                                       u'V19': { 'clipInput': True,
                                                                'fieldname': 'V3',
                                                                'maxval': 10.0,
                                                                'minval': -20.0,
                                                                'n': 50,
                                                                'name': 'V3',
                                                                'type': 'ScalarEncoder',
                                                                'w': 21},
                                                       u'V20': { 'clipInput': True,
                                                                'fieldname': 'V3',
                                                                'maxval': 10.0,
                                                                'minval': -20.0,
                                                                'n': 50,
                                                                'name': 'V3',
                                                                'type': 'ScalarEncoder',
                                                                'w': 21},
                                                       u'V21': { 'clipInput': True,
                                                                'fieldname': 'V1',
                                                                'maxval': 10.0,
                                                                'minval': -20.0,
                                                                'n': 50,
                                                                'name': 'V1',
                                                                'type': 'ScalarEncoder',
                                                                'w': 21},
                                                       u'V22': { 'clipInput': True,
                                                                'fieldname': 'V2',
                                                                'maxval': 10.0,
                                                                'minval': -20.0,
                                                                'n': 50,
                                                                'name': 'V2',
                                                                'type': 'ScalarEncoder',
                                                                'w': 21},
                                                       u'V23': { 'clipInput': True,
                                                                'fieldname': 'V3',
                                                                'maxval': 10.0,
                                                                'minval': -20.0,
                                                                'n': 50,
                                                                'name': 'V3',
                                                                'type': 'ScalarEncoder',
                                                                'w': 21},
                                                       u'V24': { 'clipInput': True,
                                                                'fieldname': 'V1',
                                                                'maxval': 10.0,
                                                                'minval': -20.0,
                                                                'n': 50,
                                                                'name': 'V1',
                                                                'type': 'ScalarEncoder',
                                                                'w': 21},
                                                       u'V25': { 'clipInput': True,
                                                                'fieldname': 'V2',
                                                                'maxval': 10.0,
                                                                'minval': -20.0,
                                                                'n': 50,
                                                                'name': 'V2',
                                                                'type': 'ScalarEncoder',
                                                                'w': 21},
                                                       u'V26': { 'clipInput': True,
                                                                'fieldname': 'V3',
                                                                'maxval': 10.0,
                                                                'minval': -20.0,
                                                                'n': 50,
                                                                'name': 'V3',
                                                                'type': 'ScalarEncoder',
                                                                'w': 21},
                                                       u'V27': { 'clipInput': True,
                                                                'fieldname': 'V1',
                                                                'maxval': 10.0,
                                                                'minval': -20.0,
                                                                'n': 50,
                                                                'name': 'V1',
                                                                'type': 'ScalarEncoder',
                                                                'w': 21},
                                                       u'V28': { 'clipInput': True,
                                                                'fieldname': 'V2',
                                                                'maxval': 10.0,
                                                                'minval': -20.0,
                                                                'n': 50,
                                                                'name': 'V2',
                                                                'type': 'ScalarEncoder',
                                                                'w': 21},
                                                       u'amount': { 'clipInput': True,
                                                                    'fieldname': 'amount',
                                                                    'maxval': 7800.0,
                                                                    'minval': 0.0,
                                                                    'n': 800,
                                                                    'name': 'amount',
                                                                    'type': 'ScalarEncoder',
                                                                    'w': 21},
                                                       u'timestamp_dayOfWeek': None,
                                                       u'timestamp_timeOfDay': { 'fieldname': 'timestamp',
                                                                                 'name': 'timestamp',
                                                                                 'timeOfDay': ( 21,
                                                                                                6.090344152692538),
                                                                                 'type': 'DateEncoder'},
                                                       u'timestamp_weekend': { 'fieldname': 'timestamp',
                                                                               'name': 'timestamp',
                                                                               'type': 'DateEncoder',
                                                                               'weekend': ( 21,
                                                                                            1)}},
                                         'sensorAutoReset': None,
                                         'verbosity': 0},
                       'spEnable': True,
                       'spParams': { 'columnCount': 2048,
                                     'globalInhibition': 1,
                                     'inputWidth': 0,
                                     'boostStrength': 2.0,
                                     'numActiveColumnsPerInhArea': 40,
                                     'potentialPct': 0.8,
                                     'seed': 1956,
                                     'spVerbosity': 0,
                                     'spatialImp': 'cpp',
                                     'synPermActiveInc': 0.05,
                                     'synPermConnected': 0.1,
                                     'synPermInactiveDec': 0.08568228006654939},
                       'tmEnable': True,
                       'tmParams': { 'activationThreshold': 12,
                                     'cellsPerColumn': 32,
                                     'columnCount': 2048,
                                     'globalDecay': 0.0,
                                     'initialPerm': 0.21,
                                     'inputWidth': 2048,
                                     'maxAge': 0,
                                     'maxSegmentsPerCell': 128,
                                     'maxSynapsesPerSegment': 32,
                                     'minThreshold': 10,
                                     'newSynapseCount': 20,
                                     'outputType': 'normal',
                                     'pamLength': 1,
                                     'permanenceDec': 0.1,
                                     'permanenceInc': 0.1,
                                     'seed': 1960,
                                     'temporalImp': 'cpp',
                                     'verbosity': 0},
                       'trainSPNetOnlyIfRequested': False},
      'predictAheadTime': None,
      'version': 1}
