MODEL_PARAMS = \
{ 'aggregationInfo': { 'days': 0,
                       'fields': [],
                       'hours': 0,
                       'microseconds': 0,
                       'milliseconds': 0,
                       'minutes': 0,
                       'months': 0,
                       'seconds': 0,
                       'weeks': 0,
                       'years': 0},
  'model': 'HTMPrediction',
  'modelParams': { 'anomalyParams': { u'anomalyCacheRecords': None,
                                      u'autoDetectThreshold': None,
                                      u'autoDetectWaitRecords': 5030},
                   # 'clEnable': False,
                   'clParams': { 'alpha': 0.01962508905154251,
                                 'verbosity': 0,
                                 'regionName': 'SDRClassifierRegion',
                                 'steps': '1'},
                   'inferenceType': 'TemporalAnomaly',
                   'sensorParams': { 'encoders': {'_classifierInput': { 'classifierOnly': True,
                                                                         'clipInput': True,
                                                                         'fieldname': 'isFraud',
                                                                         'maxval': 2.0,
                                                                         'minval': 0.0,
                                                                         'n': 22,
                                                                         'name': '_classifierInput',
                                                                         'type': 'ScalarEncoder',
                                                                         'w': 21},
                                                   u'amount': { 'clipInput': True,
                                                               'fieldname': 'amount',
                                                               'maxval': 4000000.0,
                                                               'minval': 0.0,
                                                               'n': 800,
                                                               'name': 'amount',
                                                               'type': 'ScalarEncoder',
                                                               'w': 21},
                                                   u'timestamp_timeOfDay': {
                                                       "type": "DateEncoder",
                                                       "timeOfDay": [
                                                           21,
                                                           9.49
                                                       ],
                                                       "fieldname": "timestamp",
                                                       "name": "timestamp"
                                                   },
                                                   u'timestamp_dayOfWeek': None,
                                                   u'timestamp_weekend': None},
                                                   u'paytype': {
                                                       "type": "CategoryEncoder",
                                                       "w": 4,
                                                       "categoryList": ["PAYMENT", "TRANSFER", "CASH_OUT", "CASH_IN", "DEBIT"],
                                                       "fieldname": "paytype",
                                                       "name": "paytype"},
                                                   u'oldBalanceOrig': { 'clipInput': True,
                                                                'fieldname': 'oldBalanceOrig',
                                                                'maxval': 13000000.0,
                                                                'minval': 0.0,
                                                                'n': 800,
                                                                'name': 'oldBalanceOrig',
                                                                'type': 'ScalarEncoder',
                                                                'w': 21},
                                                   u'newBalanceOrig': { 'clipInput': True,
                                                                'fieldname': 'newBalanceOrig',
                                                                'maxval': 13000000.0,
                                                                'minval': 0.0,
                                                                'n': 800,
                                                                'name': 'newBalanceOrig',
                                                                'type': 'ScalarEncoder',
                                                                'w': 21},
                                                   u'isFraud': {
                                                       'maxval': 2.0,
                                                       'minval': 0.0,
                                                       'n': 22,
                                                       'name': 'isFraud',
                                                       'type': 'ScalarEncoder',
                                                       'w': 21},
                                     'sensorAutoReset': None,
                                     'verbosity': 0},
                   'spEnable': True,
                   'spParams': { 'columnCount': 2048,
                                 'globalInhibition': 1,
                                 'inputWidth': 0,
                                 'boostStrength': 2.0,
                                 'numActiveColumnsPerInhArea': 40,
                                 'potentialPct': 0.8,
                                 'seed': 1956,
                                 'spVerbosity': 0,
                                 'spatialImp': 'cpp',
                                 'synPermActiveInc': 0.05,
                                 'synPermConnected': 0.1,
                                 'synPermInactiveDec': 0.08568228006654939},
                   'tmEnable': True,
                   'tmParams': { 'activationThreshold': 12,
                                 'cellsPerColumn': 32,
                                 'columnCount': 2048,
                                 'globalDecay': 0.0,
                                 'initialPerm': 0.21,
                                 'inputWidth': 2048,
                                 'maxAge': 0,
                                 'maxSegmentsPerCell': 128,
                                 'maxSynapsesPerSegment': 32,
                                 'minThreshold': 10,
                                 'newSynapseCount': 20,
                                 'outputType': 'normal',
                                 'pamLength': 1,
                                 'permanenceDec': 0.1,
                                 'permanenceInc': 0.1,
                                 'seed': 1960,
                                 'temporalImp': 'cpp',
                                 'verbosity': 0},
                   'trainSPNetOnlyIfRequested': False},
  'predictAheadTime': None,
  'version': 1}
